### ISSUE TITLE
Strobogrammatic - negative input

### ISSUE THREAD

**Issue by menakas** [Sahana-17/Daily-Python-Programs#1]
Make it give proper error message for negative input.

```
python strobogrammatic.py 
enter length of num : -1
Traceback (most recent call last):
  File "/Users/menakas/Children/Sahana/Daily-Python-Programs/strobogrammatic.py", line 28, in <module>
    print(gen_strobogrammatic(n))
  File "/Users/menakas/Children/Sahana/Daily-Python-Programs/strobogrammatic.py", line 6, in gen_strobogrammatic
    result = helper(n, n)
  File "/Users/menakas/Children/Sahana/Daily-Python-Programs/strobogrammatic.py", line 15, in helper
    middles = helper(n-2, length)
  File "/Users/menakas/Children/Sahana/Daily-Python-Programs/strobogrammatic.py", line 15, in helper
    middles = helper(n-2, length)
  File "/Users/menakas/Children/Sahana/Daily-Python-Programs/strobogrammatic.py", line 15, in helper
    middles = helper(n-2, length)
  [Previous line repeated 994 more times]
  File "/Users/menakas/Children/Sahana/Daily-Python-Programs/strobogrammatic.py", line 11, in helper
    if n == 0:
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by menakas** [comment]
Fixed via 11a0fcd
